version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: netfreelance_php
    volumes:
      - .:/var/www
    networks:
      - netfreelance

  nginx:
    image: nginx:alpine
    container_name: netfreelance_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - netfreelance

  database:
    image: mysql:8.0
    container_name: netfreelance_db
    environment:
      MYSQL_DATABASE: netfreelance
      MYSQL_USER: symfony
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - netfreelance

networks:
  netfreelance:
    driver: bridge

volumes:
  db_data: 